export const OPEN_MENU = 'OPEN_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';
export const SET_HEADER_CLASS = 'SET_HEADER_CLASS';

export const SET_SIGNUP_STEP = 'SET_SIGNUP_STEP';
export const SET_SIGNUP_AUTH_STEP = 'SET_SIGNUP_AUTH_STEP';
export const SET_SIGNUP_EMAIL = 'SET_SIGNUP_EMAIL';
export const SET_SIGNUP_ID = 'SET_SIGNUP_ID';
export const SET_SIGNUP_FIELDS = 'SET_SIGNUP_FIELDS';
export const RESET_STATE_SIGNUP = 'RESET_STATE_SIGNUP'

export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const SET_AUTHTOKEN = 'SET_AUTHTOKEN';
export const SET_DATA_IMPORT_COMPLETE = 'SET_DATA_IMPORT_COMPLETE';

export const SET_LWA_AUTH = 'SET_LWA_AUTH';

export const SET_QLIK_PARAMS = 'SET_QLIK_PARAMS';
export const SET_QLIK_CONNECTION = 'SET_QLIK_CONNECTION';
export const SET_QLIK_INSTANCE = 'SET_QLIK_INSTANCE';

export const CLOSE_APP_QLIK = 'CLOSE_APP_QLIK'
