export const OPEN_MENU = 'OPEN_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';
export const SET_HEADER_CLASS = 'SET_HEADER_CLASS';
export const SET_NAVBAR_DASHBOARD = 'SET_NAVBAR_DASHBOARD'
export const SET_STATUS_PROGRESS = 'SET_STATUS_PROGRESS'
export const SET_STATUS_BAR = 'SET_STATUS_BAR'

export const SET_SIGNUP_STEP = 'SET_SIGNUP_STEP';
export const SET_SIGNUP_AUTH_STEP = 'SET_SIGNUP_AUTH_STEP';
export const SET_SIGNUP_EMAIL = 'SET_SIGNUP_EMAIL';
export const SET_SIGNUP_ID = 'SET_SIGNUP_ID';
export const SET_SIGNUP_FIELDS = 'SET_SIGNUP_FIELDS';
export const RESET_STATE_SIGNUP = 'RESET_STATE_SIGNUP'
export const SET_ADD_MARKET_STEP = 'SET_ADD_MARKET_STEP'

export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const SET_AUTHTOKEN = 'SET_AUTHTOKEN';
export const SET_DATA_IMPORT_COMPLETE = 'SET_DATA_IMPORT_COMPLETE';

export const SET_LWA_AUTH = 'SET_LWA_AUTH';

export const SET_QLIK_PARAMS = 'SET_QLIK_PARAMS';
export const SET_QLIK_CONNECTION = 'SET_QLIK_CONNECTION';
export const SET_QLIK_INSTANCE = 'SET_QLIK_INSTANCE';

// dash filters
export const SET_DATA_GROUP_BY_OPTIONS = 'SET_DATA_GROUP_BY_OPTIONS';
export const SET_SELLER_ID_OPTIONS = 'SET_SELLER_ID_OPTIONS';
export const SET_MARKET_PLACE_NAME_OPTIONS = 'SET_MARKET_PLACE_NAME_OPTIONS';
export const SET_SELLER_SKU_OPTIONS = 'SET_SELLER_SKU_OPTIONS';
export const SET_DATA_GROUP_BY_SELECTED_OPTIONS = 'SET_DATA_GROUP_BY_SELECTED_OPTIONS';
export const SET_SELLER_ID_SELECTED_OPTIONS = 'SET_SELLER_ID_SELECTED_OPTIONS';
export const SET_MARKET_PLACE_NAME_SELECTED_OPTIONS = 'SET_MARKET_PLACE_NAME_SELECTED_OPTION';
export const SET_SELLER_SKU_SELECTED_OPTIONS = 'SET_SELLER_SKU_SELECTED_OPTIONS';
export const SET_CURRENT_SELECTIONS = 'SET_CURRENT_SELECTIONS';
export const SET_PICKER_START_DATE = 'SET_PICKER_START_DATE';
export const SET_PICKER_END_DATE = 'SET_PICKER_END_DATE';
export const RESET_QLIK_FILTER = 'RESET_QLIK_FILTER'
export const RESET_STATE_DASH_FILTER = 'RESET_STATE_DASH_FILTER'

export const CLOSE_APP_QLIK = 'CLOSE_APP_QLIK'
